//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEOBOX.OSC.Interlis2Converter.ConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEOBOX.OSC.Interlis2Converter.ConsoleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Angebende Typ (--type) ist ungültig..
        /// </summary>
        internal static string CMDCallTypeNotFound {
            get {
                return ResourceManager.GetString("CMDCallTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Aufruf ist ungültig..
        /// </summary>
        internal static string CMDCallWithError {
            get {
                return ResourceManager.GetString("CMDCallWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Interlis 2 Konverter.
        /// </summary>
        internal static string genModulName {
            get {
                return ResourceManager.GetString("genModulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool zur Konvertierung von Interlis 2 Dateien..
        /// </summary>
        internal static string loggerComment {
            get {
                return ResourceManager.GetString("loggerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion &apos;{0}&apos; ist fehlgeschlagen..
        /// </summary>
        internal static string MessageEndFunctionError {
            get {
                return ResourceManager.GetString("MessageEndFunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion &apos;{0}&apos; wurde erfolgreich abgeschlossen..
        /// </summary>
        internal static string MessageEndFunctionSuccess {
            get {
                return ResourceManager.GetString("MessageEndFunctionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktion &apos;{0}&apos; wurde gestartet..
        /// </summary>
        internal static string MessageStartFunction {
            get {
                return ResourceManager.GetString("MessageStartFunction", resourceCulture);
            }
        }
    }
}
