//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEOBOX.OSC.Interlis2Converter.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEOBOX.OSC.Interlis2Converter.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis &apos;{0}&apos; wurde nicht gefunden..
        /// </summary>
        internal static string DirectoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX Interlis 2 Konverter.
        /// </summary>
        internal static string genModulName {
            get {
                return ResourceManager.GetString("genModulName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokoll-Datei ist Schreibgeschützt.
        /// </summary>
        internal static string LogFileReadOnlyMessage {
            get {
                return ResourceManager.GetString("LogFileReadOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei {0} wurde nicht gefunden.
        /// </summary>
        internal static string loggerErrorCouldNotFindFile {
            get {
                return ResourceManager.GetString("loggerErrorCouldNotFindFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Namespace Alias {0} wurde mehrmals verwendet.
        /// </summary>
        internal static string loggerErrorDoubledNamespaceAliases {
            get {
                return ResourceManager.GetString("loggerErrorDoubledNamespaceAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Lesen der Datei {0}.
        /// </summary>
        internal static string loggerErrorWhileReadingFile {
            get {
                return ResourceManager.GetString("loggerErrorWhileReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim schreiben der DATASECTION mit Datei {0}.
        /// </summary>
        internal static string loggerErrorWhileWritingDatasection {
            get {
                return ResourceManager.GetString("loggerErrorWhileWritingDatasection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim schreiben der Models mit Datei {0}.
        /// </summary>
        internal static string loggerErrorWhileWritingModels {
            get {
                return ResourceManager.GetString("loggerErrorWhileWritingModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim schreiben der Namespaces.
        /// </summary>
        internal static string loggerErrorWhileWritingNamespaces {
            get {
                return ResourceManager.GetString("loggerErrorWhileWritingNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusammenführung der Dateien mit Fehler abgeschlossen.
        /// </summary>
        internal static string loggerMergingFinishedWithErrors {
            get {
                return ResourceManager.GetString("loggerMergingFinishedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusammenführung der Dateien mit Fehler und Warnungen abgeschlossen.
        /// </summary>
        internal static string loggerMergingFinishedWithErrorsAndWarnings {
            get {
                return ResourceManager.GetString("loggerMergingFinishedWithErrorsAndWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusammenführung der Dateien mit Warnungen abgeschlossen.
        /// </summary>
        internal static string loggerMergingFinishedWithWarnings {
            get {
                return ResourceManager.GetString("loggerMergingFinishedWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad {0} existiert nicht..
        /// </summary>
        internal static string loggerPathNotExisting {
            get {
                return ResourceManager.GetString("loggerPathNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte die Zusammenführung der Datein.
        /// </summary>
        internal static string loggerStartMerging {
            get {
                return ResourceManager.GetString("loggerStartMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die DATASECTION wird zusammengeführt.
        /// </summary>
        internal static string loggerStartMergingDatasection {
            get {
                return ResourceManager.GetString("loggerStartMergingDatasection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die HEADERSECTION wird zusammengeführt.
        /// </summary>
        internal static string loggerStartMergingHeadersection {
            get {
                return ResourceManager.GetString("loggerStartMergingHeadersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Namespaces werden zusammengeführt.
        /// </summary>
        internal static string loggerStartMergingNamespaces {
            get {
                return ResourceManager.GetString("loggerStartMergingNamespaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Zusammenführen der Dateien ist ein Unbekannter Fehler aufgetreten.
        /// </summary>
        internal static string loggerUnknownErrorWhileMerging {
            get {
                return ResourceManager.GetString("loggerUnknownErrorWhileMerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: DMAV Zusammenführen zu einer Datei (DMAV alles)..
        /// </summary>
        internal static string MergeDMAVDisplayName {
            get {
                return ResourceManager.GetString("MergeDMAVDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel-Datei ist Schreibgeschützt.
        /// </summary>
        internal static string OutputFileReadOnlyMessage {
            get {
                return ResourceManager.GetString("OutputFileReadOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel-Datei ist vorhanden, kann diese Überscchrieben werden?.
        /// </summary>
        internal static string OverwriteMeassgeOutputFile {
            get {
                return ResourceManager.GetString("OverwriteMeassgeOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziel-Datei und Protokoll-Datei sind vorhanden, können diese Überscchrieben werden?.
        /// </summary>
        internal static string OverwriteMessageAllFiles {
            get {
                return ResourceManager.GetString("OverwriteMessageAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protokoll-Datei ist vorhanden, kann diese Überscchrieben werden?.
        /// </summary>
        internal static string OverwriteMessageLogFile {
            get {
                return ResourceManager.GetString("OverwriteMessageLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien können überschrieben werden..
        /// </summary>
        internal static string OverwriteMessageOk {
            get {
                return ResourceManager.GetString("OverwriteMessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOBOX.Interlis2Konverter.
        /// </summary>
        internal static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
    }
}
